### ISSUE TITLE
relation "tag_cache" does not exist  - relation "model_name_cache" does not exist

### ISSUE THREAD

**Issue by guidev** [lunary-ai/lunary#127]
Hi,
I'm getting this error 

```
npm run dev

> lunary@1.0.0 dev
> concurrently "npm run frontend:dev" "npm run backend:dev"

[0]
[0] > lunary@1.0.0 frontend:dev
[0] > npm -w packages/frontend run dev
[0]
[1]
[1] > lunary@1.0.0 backend:dev
[1] > npm -w packages/backend run dev
[1]
[0]
[0] > dev
[0] > next dev -p 8080
[0]
[1]
[1] > dev
[1] > tsx --env-file=.env --watch src/index.ts
[1]
[1] (node:9072) ExperimentalWarning: Watch mode is an experimental feature and might change at any time
[1] (Use `node --trace-warnings ...` to show where the warning was created)
[0]    ▲ Next.js 14.1.0
[0]    - Local:        http://localhost:8080
[0]
[0] `destination` does not start with `/`, `http://`, or `https://` for route {"source":"/api/v1/report","destination":"undefined/api/report"}
[0]
[0] `destination` does not start with `/`, `http://`, or `https://` for route {"source":"/api/report","destination":"undefined/api/report"}
[0]
[0] `destination` does not start with `/`, `http://`, or `https://` for route {"source":"/api/v1/template","destination":"undefined/api/v1/template"}
[0]
[0]
[0] Error: Invalid rewrites found
[0]
[0] npm run frontend:dev exited with code 0
[1] ✅ Lunary API server listening on port 3333
[1] ✅ Connected to database
[1] [JOB]: refreshing `model_name_cache`
[1] [JOB]: refreshing `tag_cache`
[1] PostgresError: relation "model_name_cache" does not exist
[1]     at ErrorResponse (/home/ec2-user/lunary/node_modules/postgres/cjs/src/connection.js:790:26)
[1]     at handle (/home/ec2-user/lunary/node_modules/postgres/cjs/src/connection.js:476:6)
[1]     at Socket.data (/home/ec2-user/lunary/node_modules/postgres/cjs/src/connection.js:315:9)
[1]     at Socket.emit (node:events:518:28)
[1]     at Socket.emit (node:domain:488:12)
[1]     at addChunk (node:internal/streams/readable:559:12)
[1]     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
[1]     at Readable.push (node:internal/streams/readable:390:5)
[1]     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[1]     at cachedError (/home/ec2-user/lunary/node_modules/postgres/cjs/src/query.js:170:23)
[1]     at new Query (/home/ec2-user/lunary/node_modules/postgres/cjs/src/query.js:36:24)
[1]     at Object.sql (/home/ec2-user/lunary/node_modules/postgres/cjs/src/index.js:112:11)
[1]     at Task.import_node_cron.default.schedule.name (/home/ec2-user/lunary/packages/backend/src/utils/cron.ts:14:15) {
[1]   severity_local: 'ERROR',
[1]   severity: 'ERROR',
[1]   code: '42P01',
[1]   file: 'namespace.c',
[1]   line: '433',
[1]   routine: 'RangeVarGetRelidExtended'
[1] }
[1] PostgresError: relation "tag_cache" does not exist
[1]     at ErrorResponse (/home/ec2-user/lunary/node_modules/postgres/cjs/src/connection.js:790:26)
[1]     at handle (/home/ec2-user/lunary/node_modules/postgres/cjs/src/connection.js:476:6)
[1]     at Socket.data (/home/ec2-user/lunary/node_modules/postgres/cjs/src/connection.js:315:9)
[1]     at Socket.emit (node:events:518:28)
[1]     at Socket.emit (node:domain:488:12)
[1]     at addChunk (node:internal/streams/readable:559:12)
[1]     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
[1]     at Readable.push (node:internal/streams/readable:390:5)
[1]     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[1]     at cachedError (/home/ec2-user/lunary/node_modules/postgres/cjs/src/query.js:170:23)
[1]     at new Query (/home/ec2-user/lunary/node_modules/postgres/cjs/src/query.js:36:24)
[1]     at Object.sql (/home/ec2-user/lunary/node_modules/postgres/cjs/src/index.js:112:11)
[1]     at Task.import_node_cron.default.schedule.name (/home/ec2-user/lunary/packages/backend/src/utils/cron.ts:27:15) {
[1]   severity_local: 'ERROR',
[1]   severity: 'ERROR',
[1]   code: '42P01',
[1]   file: 'namespace.c',
[1]   line: '433',
[1]   routine: 'RangeVarGetRelidExtended'
[1] }
[1] [JOB]: refreshing `model_name_cache`
[1] [JOB]: refreshing `tag_cache`
[1] PostgresError: relation "model_name_cache" does not exist
[1]     at ErrorResponse (/home/ec2-user/lunary/node_modules/postgres/cjs/src/connection.js:790:26)
[1]     at handle (/home/ec2-user/lunary/node_modules/postgres/cjs/src/connection.js:476:6)
[1]     at Socket.data (/home/ec2-user/lunary/node_modules/postgres/cjs/src/connection.js:315:9)
[1]     at Socket.emit (node:events:518:28)
[1]     at Socket.emit (node:domain:488:12)
[1]     at addChunk (node:internal/streams/readable:559:12)
[1]     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
[1]     at Readable.push (node:internal/streams/readable:390:5)
[1]     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[1]     at cachedError (/home/ec2-user/lunary/node_modules/postgres/cjs/src/query.js:170:23)
[1]     at new Query (/home/ec2-user/lunary/node_modules/postgres/cjs/src/query.js:36:24)
[1]     at Object.sql (/home/ec2-user/lunary/node_modules/postgres/cjs/src/index.js:112:11)
[1]     at Task.import_node_cron.default.schedule.name (/home/ec2-user/lunary/packages/backend/src/utils/cron.ts:14:15) {
[1]   severity_local: 'ERROR',
[1]   severity: 'ERROR',
[1]   code: '42P01',
[1]   file: 'namespace.c',
[1]   line: '433',
[1]   routine: 'RangeVarGetRelidExtended'
[1] }
[1] PostgresError: relation "tag_cache" does not exist
[1]     at ErrorResponse (/home/ec2-user/lunary/node_modules/postgres/cjs/src/connection.js:790:26)
[1]     at handle (/home/ec2-user/lunary/node_modules/postgres/cjs/src/connection.js:476:6)
[1]     at Socket.data (/home/ec2-user/lunary/node_modules/postgres/cjs/src/connection.js:315:9)
[1]     at Socket.emit (node:events:518:28)
[1]     at Socket.emit (node:domain:488:12)
[1]     at addChunk (node:internal/streams/readable:559:12)
[1]     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
[1]     at Readable.push (node:internal/streams/readable:390:5)
[1]     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[1]     at cachedError (/home/ec2-user/lunary/node_modules/postgres/cjs/src/query.js:170:23)
[1]     at new Query (/home/ec2-user/lunary/node_modules/postgres/cjs/src/query.js:36:24)
[1]     at Object.sql (/home/ec2-user/lunary/node_modules/postgres/cjs/src/index.js:112:11)
[1]     at Task.import_node_cron.default.schedule.name (/home/ec2-user/lunary/packages/backend/src/utils/cron.ts:27:15) {
[1]   severity_local: 'ERROR',
[1]   severity: 'ERROR',
[1]   code: '42P01',
[1]   file: 'namespace.c',
[1]   line: '433',
[1]   routine: 'RangeVarGetRelidExtended'
[1] }
[1] [JOB]: refreshing `model_name_cache`
[1] [JOB]: refreshing `tag_cache`
[1] PostgresError: relation "model_name_cache" does not exist
[1]     at ErrorResponse (/home/ec2-user/lunary/node_modules/postgres/cjs/src/connection.js:790:26)
[1]     at handle (/home/ec2-user/lunary/node_modules/postgres/cjs/src/connection.js:476:6)
[1]     at Socket.data (/home/ec2-user/lunary/node_modules/postgres/cjs/src/connection.js:315:9)
[1]     at Socket.emit (node:events:518:28)
[1]     at Socket.emit (node:domain:488:12)
[1]     at addChunk (node:internal/streams/readable:559:12)
[1]     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
[1]     at Readable.push (node:internal/streams/readable:390:5)
[1]     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[1]     at cachedError (/home/ec2-user/lunary/node_modules/postgres/cjs/src/query.js:170:23)
[1]     at new Query (/home/ec2-user/lunary/node_modules/postgres/cjs/src/query.js:36:24)
[1]     at Object.sql (/home/ec2-user/lunary/node_modules/postgres/cjs/src/index.js:112:11)
[1]     at Task.import_node_cron.default.schedule.name (/home/ec2-user/lunary/packages/backend/src/utils/cron.ts:14:15) {
[1]   severity_local: 'ERROR',
[1]   severity: 'ERROR',
[1]   code: '42P01',
[1]   file: 'namespace.c',
[1]   line: '433',
[1]   routine: 'RangeVarGetRelidExtended'
[1] }
[1] PostgresError: relation "tag_cache" does not exist
[1]     at ErrorResponse (/home/ec2-user/lunary/node_modules/postgres/cjs/src/connection.js:790:26)
[1]     at handle (/home/ec2-user/lunary/node_modules/postgres/cjs/src/connection.js:476:6)
[1]     at Socket.data (/home/ec2-user/lunary/node_modules/postgres/cjs/src/connection.js:315:9)
[1]     at Socket.emit (node:events:518:28)
[1]     at Socket.emit (node:domain:488:12)
[1]     at addChunk (node:internal/streams/readable:559:12)
[1]     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
[1]     at Readable.push (node:internal/streams/readable:390:5)
[1]     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[1]     at cachedError (/home/ec2-user/lunary/node_modules/postgres/cjs/src/query.js:170:23)
[1]     at new Query (/home/ec2-user/lunary/node_modules/postgres/cjs/src/query.js:36:24)
[1]     at Object.sql (/home/ec2-user/lunary/node_modules/postgres/cjs/src/index.js:112:11)
[1]     at Task.import_node_cron.default.schedule.name (/home/ec2-user/lunary/packages/backend/src/utils/cron.ts:27:15) {
[1]   severity_local: 'ERROR',
[1]   severity: 'ERROR',
[1]   code: '42P01',
[1]   file: 'namespace.c',
[1]   line: '433',
[1]   routine: 'RangeVarGetRelidExtended'
[1] }
[1] [JOB]: refreshing `model_name_cache`
[1] [JOB]: refreshing `tag_cache`
[1] PostgresError: relation "model_name_cache" does not exist
[1]     at ErrorResponse (/home/ec2-user/lunary/node_modules/postgres/cjs/src/connection.js:790:26)
[1]     at handle (/home/ec2-user/lunary/node_modules/postgres/cjs/src/connection.js:476:6)
[1]     at Socket.data (/home/ec2-user/lunary/node_modules/postgres/cjs/src/connection.js:315:9)
[1]     at Socket.emit (node:events:518:28)
[1]     at Socket.emit (node:domain:488:12)
[1]     at addChunk (node:internal/streams/readable:559:12)
[1]     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
[1]     at Readable.push (node:internal/streams/readable:390:5)
[1]     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[1]     at cachedError (/home/ec2-user/lunary/node_modules/postgres/cjs/src/query.js:170:23)
[1]     at new Query (/home/ec2-user/lunary/node_modules/postgres/cjs/src/query.js:36:24)
[1]     at Object.sql (/home/ec2-user/lunary/node_modules/postgres/cjs/src/index.js:112:11)
[1]     at Task.import_node_cron.default.schedule.name (/home/ec2-user/lunary/packages/backend/src/utils/cron.ts:14:15) {
[1]   severity_local: 'ERROR',
[1]   severity: 'ERROR',
[1]   code: '42P01',
[1]   file: 'namespace.c',
[1]   line: '433',
[1]   routine: 'RangeVarGetRelidExtended'
[1] }
[1] PostgresError: relation "tag_cache" does not exist
[1]     at ErrorResponse (/home/ec2-user/lunary/node_modules/postgres/cjs/src/connection.js:790:26)
[1]     at handle (/home/ec2-user/lunary/node_modules/postgres/cjs/src/connection.js:476:6)
[1]     at Socket.data (/home/ec2-user/lunary/node_modules/postgres/cjs/src/connection.js:315:9)
[1]     at Socket.emit (node:events:518:28)
[1]     at Socket.emit (node:domain:488:12)
[1]     at addChunk (node:internal/streams/readable:559:12)
[1]     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
[1]     at Readable.push (node:internal/streams/readable:390:5)
[1]     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[1]     at cachedError (/home/ec2-user/lunary/node_modules/postgres/cjs/src/query.js:170:23)
[1]     at new Query (/home/ec2-user/lunary/node_modules/postgres/cjs/src/query.js:36:24)
[1]     at Object.sql (/home/ec2-user/lunary/node_modules/postgres/cjs/src/index.js:112:11)
[1]     at Task.import_node_cron.default.schedule.name (/home/ec2-user/lunary/packages/backend/src/utils/cron.ts:27:15) {
[1]   severity_local: 'ERROR',
[1]   severity: 'ERROR',
[1]   code: '42P01',
[1]   file: 'namespace.c',
[1]   line: '433',
[1]   routine: 'RangeVarGetRelidExtended'
[1] }
```

**Comment by guidev** [comment]
I've noticed that the db was empty, I manually ran the init.sql and not the error goes away. 

However, it's still not working: 


```
curl http://localhost:8080
curl: (7) Failed to connect to localhost port 8080 after 0 ms: Connection refused
```




```
npm run dev

> lunary@1.0.0 dev
> concurrently "npm run frontend:dev" "npm run backend:dev"

[0]
[0] > lunary@1.0.0 frontend:dev
[0] > npm -w packages/frontend run dev
[0]
[1]
[1] > lunary@1.0.0 backend:dev
[1] > npm -w packages/backend run dev
[1]
[0]
[0] > dev
[0] > next dev -p 8080
[0]
[1]
[1] > dev
[1] > tsx --env-file=.env --watch src/index.ts
[1]
[1] (node:7154) ExperimentalWarning: Watch mode is an experimental feature and might change at any time
[1] (Use `node --trace-warnings ...` to show where the warning was created)
[0]    ▲ Next.js 14.1.0
[0]    - Local:        http://localhost:8080
[0]
[0] `destination` does not start with `/`, `http://`, or `https://` for route {"source":"/api/v1/report","destination":"undefined/api/report"}
[0]
[0] `destination` does not start with `/`, `http://`, or `https://` for route {"source":"/api/report","destination":"undefined/api/report"}
[0]
[0] `destination` does not start with `/`, `http://`, or `https://` for route {"source":"/api/v1/template","destination":"undefined/api/v1/template"}
[0]
[0]
[0] Error: Invalid rewrites found
[0]
[0] npm run frontend:dev exited with code 0
[1] ✅ Lunary API server listening on port 3333
[1] ✅ Connected to database
[1] [JOB]: refreshing `model_name_cache`
[1] [JOB]: refreshing `tag_cache`

[1] [JOB]: refreshing `model_name_cache`
[1] [JOB]: refreshing `tag_cache`


```

**Comment by guidev** [comment]
any update?

**Comment by hughcrt** [comment]
Hi @guidev , I've updated the `init.sql` file. The instructions for running lunary locally are here: https://github.com/lunary-ai/lunary/blob/fe47af01f06cfbcfe9504699522c414c3c745036/CONTRIBUTING.md

Please let me know if you still get this issue
