### ISSUE TITLE
Errors while self hosting

### ISSUE THREAD

**Issue by kaaancan** [lunary-ai/lunary#141]
Hey,

i tried all the steps, i could log in into the APP and the database has a connection and also some requests are logged.

When i open up the APP and go to logs i get the following backend error:

TypeError: (0 , import_shared.deserializeLogic) is not a function
[1]     at <anonymous> (/Users/kaancan/oss/lunary/packages/backend/src/api/v1/runs/index.ts:95:31)
[1]     at dispatch (/Users/kaancan/oss/lunary/packages/backend/node_modules/koa-compose/index.js:42:32)
[1]     at /Users/kaancan/oss/lunary/packages/backend/node_modules/koa-router/lib/router.js:423:16
[1]     at dispatch (/Users/kaancan/oss/lunary/packages/backend/node_modules/koa-compose/index.js:42:32)
[1]     at /Users/kaancan/oss/lunary/packages/backend/node_modules/koa-compose/index.js:34:12
[1]     at dispatch (/Users/kaancan/oss/lunary/packages/backend/node_modules/koa-router/lib/router.js:428:31)
[1]     at dispatch (/Users/kaancan/oss/lunary/packages/backend/node_modules/koa-compose/index.js:42:32)
[1]     at dispatch (/Users/kaancan/oss/lunary/packages/backend/node_modules/koa-router/lib/router.js:397:32)
[1]     at dispatch (/Users/kaancan/oss/lunary/packages/backend/node_modules/koa-compose/index.js:42:32)
[1]     at setDefaultBody (/Users/kaancan/oss/lunary/packages/backend/src/utils/misc.ts:5:9) {
[1]   headers: {
[1]     'Access-Control-Allow-Origin': 'http://localhost:8080',
[1]     'Access-Control-Allow-Credentials': 'true',
[1]     vary: 'Origin'
[1]   }
[1] }

I have used the latest bun version while installing the deps and running the app locally with the bun run dev command

Would appreciate help here 🙏

**Comment by hughcrt** [comment]
Hi, can you try with npm and node? We do not support bun

**Comment by kaaancan** [comment]
Thanks its working now, i was confused since the README.md of the backend package stated to use bun.

**Comment by hughcrt** [comment]
Whoops, we've forgotten to remove that
